Initial support for GPUs in Redecomp and the Tribol MFEM interface
LLNL/Tribol pull request #56
Opened 2024-01-30 19:46 UTC by ebchin

This PR adds initial support for GPU data in the Redecomp library using MFEM's built in GPU support.

Transfers from parallel data (grid functions and quadrature functions) on device to redecomp data are done as follows:

1. Device parallel data is copied to host using `mfem::Vector::HostRead()`.
2. MPI communication moves host data from parallel rank to its redecomp rank.
3. Host redecomp data is written to a host pointer obtained using `mfem::Vector::HostWrite()`.

The final result is redecomp data on the host, which can be copied to the GPU as needed in MFEM.  Transfers from redecomp data to parallel data are done in reverse order.

The support for GPU data is extended to the Tribol MFEM interface, which leverages the Redecomp library to prepare data for processing by Tribol.  Since Tribol does not support GPUs, redecomp data is left on host where Tribol can compute contact contributions.

GPU support has been added to the following examples:

1. `domain_redecomp.cpp`: use the Redecomp library to transfer parallel data on device to redecomp data on device and back
2. `mfem_common_plane.cpp`: multirank common plane contact using MFEM (with GPU) and Tribol
3. `mfem_mortar_lm_patch.cpp`: multirank contact patch test using MFEM (with GPU) and Tribol mortar

TODO:

1. Potentially add GPU support to other examples
2. Add GPU support to relevant tests

2024-02-15 04:09 UTC, srwopschall requested changes
@ebchin - This looks good so far. I mostly have clarity type comments in this first pass. This mostly covers the examples so far.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // device configuration string (see mfem::Device::Configure())
Maybe a short note on why you would see mfem::Device::Configure()? E.g. see mfem::Device::Configure() for device configuration options? Or is it something else?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +    "Device configuration string, see mfem::Device::Configure().")
See note above for minor clarity comment.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  mfem::Device device(device_config);
Does this constructor do error checking on 'device_config' or should you do that here?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // move data to device (if device is available) and set host flag to stale
Consider clarifying what 'data' is being moved, and what the intent is here. We spoke about how while a parmesh is always on host, various data underneath that parmesh can be sent to device. In terms of this example, what is the intent here? Consider explaining briefly.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // redecomp does transfers on host, so par_x_ref_elem data will be copied to
Just checking: This routine `TransferToSerial()` will take care of copying the par_x_ref_elem data back to host if it is on device, and then to the transfer to serial?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // move data to device (if device is available) and set host flag to stale
What does it mean to have a host flag set to stale? Might just clarify in one location in this example.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // copy redecomp data to device and set host flag to stale
Clarify what data is being copied. Is this just the nodal coordinates? For now as we are getting into this I think it is good to be very clear about this to avoid confusion of what is copied when, where, why from device to host etc. as we port these algorithms.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // redecomp does transfers on host, so par_x_ref_node data will be copied to
See notes at same point in element-by-element transfer to see if additional clarity is needed.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // copy redecomp data to device and set host flag to stale
Clarify what the redecomp data is.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // redecomp does transfers on host, so redecomp_x_ref_elem data will be
See previous test comments.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // redecomp does transfers on host, so redecomp_x_ref_node data will be
See previous comments about clarity here.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // copy redecomp data to device and set host flag to stale
For clarity, the redecomp data is the quad function that has been transfered from the original decomposition to serial? Please clarify if you think it is needed.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/element_matrix_redecomp.cpp
> +  // device configuration string (see mfem::Device::Configure())
Here and line 82, consider clarifying on what seeing mfem::Device::Configure() will do for a person new to this example.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/element_matrix_redecomp.cpp
> +  mfem::Device device(device_config);
I don't see any other gpu specific code in this example. Looks like the example just takes in the device_config. Can you clarify the intent or anything I may be missing in my cursory review of this?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // device configuration string (see mfem::Device::Configure())
Same clarity comment here.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +    "Device configuration string, see mfem::Device::Configure().")
Clarity.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +    serial_mesh.UniformRefinement();
Do we no longer need to guard this against <=0 ref_levels?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  mfem::ParMesh mesh(MPI_COMM_WORLD, serial_mesh);
Minor: Consider calling this 'pmesh' since you do make the distinction earlier of a serial_mesh?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
>   * @brief Demonstrates explicit contact using Tribol's common plane algorithm
I can't easily tell if this example itself transfers anything to device to then use the redecomp + gpu code in this PR. Can you clarify? Another way of stating this, does this example put/run anything on device? Can you clarify where this happens?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  // device configuration string (see mfem::Device::Configure())
Clarity about the mfem::Device::Configure() here and line 106 per previous comments.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  mfem::ParMesh mesh(MPI_COMM_WORLD, serial_mesh);
Consider pmesh for clarity?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
>    a.AddDomainIntegrator(new mfem::ElasticityIntegrator(lambda_coeff, mu_coeff));
Alluding to my comment in the mfem common plane example, if you have set the device_config with mfem, then are domain integrator calculations on the gpu if that is what is specified? In that way, based on the device_config, all that is under the hood in mfem? Might be worth making a note of that for those who may look at this example and are less familiar with mfem / gpus

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
>    tribol::registerMfemCouplingScheme(
Again, just for my clarification, if we set the device_config to use gpus, will redecomp need to copy anything from device to host similar to what you show in your redecomp example? Will the nodal coords be put on the gpu? Consider clarifying what exactly setting the device_config for gpus will do in terms of what data will be on device for these examples.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  mfem::Vector B_blk(A_blk->Height());
block RHS vector for forces and gaps makes sense. Why change it? Don't necessarily need to 'block' designation/functionality? You stil call it B_blk though. If I just saw the new code I wouldn't question it, just wondering in the context of these diffs.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  B_blk.UseDevice(true);
Consider adding a comment here about what UseDevice() will do when set to true. This sounds obvious, but this is specifically a new line of code that enables use of the gpu. Should we always set this to true, or should we set it based on device_config (if that is appropriate)? Seems like we would want it to be false if we want to run this example on cpu only?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  gap.UseDevice(true);
Same comment about whether we always want 'true' to be passed in here.

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  mfem::Vector X_blk(A_blk->Width());
Again, clarify the move from a block vector to a vector?

2024-02-15 04:09 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
>    solver.Mult(B_blk, X_blk);
This solve will be on device if true is passed to both B_blk.UseDevice() and X_blk.UseDevice()?

2024-02-15 19:59 UTC, ebchin commented on src/examples/domain_redecomp.cpp
> +  mfem::Device device(device_config);
It's verified here: https://github.com/mfem/mfem/blob/master/general/device.cpp#L207

2024-02-15 20:20 UTC, ebchin commented on src/examples/domain_redecomp.cpp
> +  // redecomp does transfers on host, so par_x_ref_elem data will be copied to
Yes, indirectly.  The [`GetSubVector()`](https://github.com/mfem/mfem/blob/master/linalg/vector.cpp#L579) method [called here](https://github.com/LLNL/Tribol/blob/gpu_testing/src/redecomp/transfer/TransferByElements.cpp#L54) will get the correct pointer and make sure the DOF data is up-to-date.

2024-02-15 21:22 UTC, ebchin commented on src/examples/element_matrix_redecomp.cpp
> +  mfem::Device device(device_config);
I'll have to verify, but I think this example doesn't do anything on GPU yet.

2024-02-15 21:25 UTC, ebchin commented on src/examples/mfem_common_plane.cpp
> +    serial_mesh.UniformRefinement();
This was copied/pasted from an old MFEM example.  Seemed unnecessary since if ref_levels <= 0, then it would never go through the for loop.

2024-02-15 21:27 UTC, ebchin commented on src/examples/mfem_common_plane.cpp
> +  mfem::ParMesh mesh(MPI_COMM_WORLD, serial_mesh);
I'll keep it as `mesh`. This seems to be the way the MFEM examples are going (see https://github.com/mfem/mfem/blob/master/examples/ex0p.cpp#L42), so the consistency might be helpful.

2024-02-17 00:45 UTC, ebchin commented
@srwopschall, I think your comments are addressed in the latest commit.  Let's discuss what kind of comments are appropriate in the MFEM examples, as the things that will be computed on device vs. host there are a bit in flux.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  mfem::Device device(device_config);
Mention what device_config option(s) you have tested, run. Maybe one is just fine for the purposes of this PR.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // Copy DOF data to device (if device is available), set host data as invalid,
Consider taking this out of example and ensuring it is in appropriate test.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // to host and the device DOF data of redecomp_x_ref_elem will be marked as
"[...] to host (if the data is on device)..."

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  redecomp_x_ref_elem.ReadWrite();
take this out. A user/host-code won't need to make this call.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  redecomp_x_ref_node.ReadWrite();
take this ReadWrite() out.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  app.add_option("-d,--device", device_config,
Keep in here for future gpu options?

2024-02-23 21:42 UTC, srwopschall commented on src/examples/element_matrix_redecomp.cpp
> +  // enable devices such as GPUs
```suggestion
  // allow use of MFEM GPU-kernals
```

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // enable devices such as GPUs
```suggestion
  // allow use of MFEM GPU-kernals
```

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // MFEM), but mass inversion is done on device. These are only computed once, then stored on device.
1) Minor (if you decide to keep this comment in spirit of what's done on cpu vs gpu): but mass inversion is done on device if `device_config` enables GPU kernals.

2) OR: take this comment out. If a user of this example enables gpus using device_config, we shouldn't explicitly state what is on CPU vs GPU because that may change.

Leaning toward (2).

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  // enable devices such as GPUs
Update this comment per other examples.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  coords.ReadWrite();
Let's remove this, but verify this is in the test? Remove comment here too.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  coords.ReadWrite();
Remove this and the comment. Verify if this line is needed in the test.

2024-02-23 21:42 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  mfem::Vector B_blk(A_blk->Height());
If you stick with mfem::Vector, consider renaming B_blk to just B, and similiarly for A, unless you are actually storing one block of data.

2025-11-04 18:55 UTC, srwopschall reviewed
Review 1. Minor clarifying review comments and a few notes to discuss.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> + *   1. Create a RedecompMesh by providing a parent ParMesh (and optionally a method of repartitioning the domain)
Is specifying a method for repartitioning the domain something we support right now? If not, remove locations where this is mentioned.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> + * Example output on both the RedecompMesh and the ParMesh can be viewed in VisIt.
Consider mentioning the field names that one would want to find or visualize in visit.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // "cpu" and "cuda"
is cpu and cuda still accurate?

2025-11-04 18:55 UTC, srwopschall commented on src/examples/domain_redecomp.cpp
> +  // 0 < max_out_of_balance <= 1; determines the maximum proportion the number of elements in each partition is allowed
Did any of the work on fixing out of balance warnings etc. render this comment inaccurate?

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> + * The example uses the Tribol MFEM interface, which supports decomposed (MPI) meshes and has experimental support for
Update comment if we are no longer considering HO mesh support + LOR as experimental.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> + * higher order meshes using low-order refinement of higher-order geometry representations. Comments in the main
Minor: for consistency let's use "high-order"

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +#include "shared/mesh/MeshBuilder.hpp"
Per your comment above about experimental support for HO meshes + LOR, does the mesh builder have support to build HO meshes?

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
>    int order = 1;
Consider a clarifying comment if order has to be 1, or if a user/developer could have order > 1 if the mesh builder can support this.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> -  std::string mesh_file = TRIBOL_REPO_DIR "/data/two_hex_apart.mesh";
Maybe I'm missing it, but where is the mesh file specified now?

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  auto contact_surf_1 = std::set<int>( { 6 } );
Any particular reason the boundary attribute integers changed?

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +      .updateAttrib( 1, 2 )
Consider commenting what the integer values represent for clarity.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // re-decomposing the domain to move spatially close surface element pairs on to the same rank, and 4) creating a
Minor. Try to be consistent when referring to the MFEM mesh. Is it a parmesh you are referring to? Between parmesh, par submesh, serial redecomp mesh and what happens where on host vs. device I think being explicit with these references is good. Also, consider "proximate" vs. "close". "on to" should be onto (?).

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // updateMfemParallelDecomposition(), which is typically called before calling update().
Minor: "tribol::update()"

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_common_plane.cpp
> +  // This API call adds a velocity field to the coupling scheme. This is used for computing the maximum common plane
Should be "minimum" common plane time step. If the common plane timestep is less than the current explicit operators timestep then we ideally lower the dt and repeat the step.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> +  // Next, we create a Tribol coupling scheme between the contact surfaces on the MFEM mesh. To create the coupling
Similar minor comment about being explicit about what is a parallel object vs. serial object.

2025-11-04 18:55 UTC, srwopschall commented on src/examples/mfem_mortar_lm_patch.cpp
> -#include "redecomp/redecomp.hpp"
It looks like redecomp is used in this example. Is the header included elsewhere?

2025-11-04 18:55 UTC, srwopschall commented on src/tests/redecomp_transfer.cpp
> +  xfer_quad_fn_->Read();
clarify why you have the "Read()" call on the xfer_quad_fn_, while the other tests you don't call Read() on the xfer_ pointer.

2025-11-04 18:55 UTC, srwopschall commented on src/tests/tribol_mfem_common_plane.cpp
> +    tribol::RealT initial_v = 0.0;
Confirm changing the nonzero initial velocity to a zero initial velocity.

2025-11-04 18:55 UTC, srwopschall commented on src/tests/tribol_mfem_common_plane.cpp
> +        .updateAttrib( 1, 2 )
Consider clarifying what all the integers are.

2025-11-04 18:55 UTC, srwopschall commented on src/tests/tribol_mfem_mortar_lm.cpp
> +    mfem::Array2D<const mfem::HypreParMatrix*> hypre_blocks( 2, 2 );
Minor: I think this block of code is clear, but consider a brief comment as to what is being done here.

2025-11-04 18:55 UTC, srwopschall commented on src/tests/tribol_mfem_mortar_lm.cpp
> +  mfem::Device device( "cuda" );
Confirm that we'd only run on cpu or cuda.

2025-11-04 18:55 UTC, srwopschall commented on src/tribol/common/BasicTypes.hpp
> +#error "TRIBOL_USE_CUDA or TRIBOL_USE_HIP but __device__ is undefined.  Check include files"
Consider elaborating on "Check include files"

2025-11-04 18:55 UTC, srwopschall commented on src/tribol/common/Containers.hpp
> +  TRIBOL_DEFAULT_HOST_DEVICE ~DeviceArray() = default;
Can you clarify why you modified this to include "DEFAULT"?

2025-11-04 18:55 UTC, srwopschall commented on src/tribol/interface/mfem_tribol.cpp
> +    SLIC_ERROR_ROOT_IF( !mfem::Device::Allows( mfem::Backend::CUDA_MASK ), "CUDA execution is not enabled in MFEM." );
Let's discuss when/where/how TRIBOL_USE_CUDA could be defined, for example, but CUDA is not enabled in MFEM.

2025-11-04 18:55 UTC, srwopschall commented on src/tribol/interface/mfem_tribol.cpp
> +    SLIC_ERROR_ROOT_IF( !mfem::Device::Allows( mfem::Backend::CUDA_MASK ), "CUDA execution is not enabled in MFEM." );
Additionally, we probably want to error out here because we are in some inconsistent build state, for lack of a better term, but let's discuss this.

2025-11-04 18:55 UTC, srwopschall commented on src/tribol/mesh/CouplingScheme.cpp
> +  if ( !isOnDevice( this->m_exec_mode ) ) {
I think we want to be able to run common plane on device, but write interface output on host? Let's discuss. Interface output is arguably mainly for debugging, which we could relegate to host only, but let's discuss this.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.hpp
> +   * @param use_ea Whether to use device-friendly element assembly for the transfer (default: false)
Perhaps elaborate on what device-friendly means here. If we are running common plane on device, will we typically want this to be `true` for HO + LOR?

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.hpp
> +   * @param use_device If true, use device memory for the redecomp grid function
Would it ever be the case that you are running contact on the GPU, but NOT actually want to use device memory here? That is, do we need this boolean? Or, can this routine perform some execution policy check and then use device memory as required?

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.hpp
> +    UpdateData( ParentRedecompTransfer& parent_redecomp_xfer, const mfem::ParGridFunction& parent_gridfn,
Same general comment re the device boolean. Let's discuss for clarity.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.hpp
> +    int allocator_id_;
It is a little hard for me to see in the diffs, but there is an allocator_id_ here on line 1159 and later on 1398. Double check that this is correct.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +  parent_dst.SyncMemory( parent_gridfn );
Just a note to discuss SyncMemory. These calls appear to be new.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +    // Tribol only computes on host
I'm not sure I follow this comment given the lines of code below it. Clarify.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +    // Tribol only computes on host
Does this comment make sense?

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +    auto data = GetRedecompGridFn().HostRead();
This is a different call (or way to get the data) than in L204 or L191. Please confirm/clarify.

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +    tribol_elem_thickness_1_ = std::make_unique<ArrayT<RealT>>(
I'm moving through this block quickly. It just looks like updating the data types to use the array views?

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/mesh/MfemData.cpp
> +      std::make_unique<SubmeshLORTransfer>( *submesh_xfer_gridfn_.ParFESpace(), *lor_mesh_, use_device_ );
Clarify the need for use_device_ since elsewhere it is stated that submesh can't do transfer on device. Is this just then hard coded to false somewhere, but left as an argument if/when submesh does do transfer on device?

2025-11-04 21:44 UTC, srwopschall commented on src/tribol/utils/TestUtils.hpp
> -  void SetHomogeneousBC( mfem::Vector& dxdt ) const;
Was this just never used?

2025-11-06 18:12 UTC, ebchin commented on src/examples/domain_redecomp.cpp
> +  // "cpu" and "cuda"
get rid of the specific devices

2025-11-06 18:14 UTC, ebchin commented on src/examples/mfem_common_plane.cpp
> + * The example uses the Tribol MFEM interface, which supports decomposed (MPI) meshes and has experimental support for
fix, no longer experimental

2025-11-06 18:23 UTC, ebchin commented on src/examples/mfem_common_plane.cpp
> +      .updateAttrib( 1, 2 )
add notes -- where are the boundary attributes on the mesh

2025-11-06 18:26 UTC, ebchin commented on src/examples/mfem_common_plane.cpp
> +  // This API call adds a velocity field to the coupling scheme. This is used for computing the maximum common plane
maximum allowable

2025-11-06 18:37 UTC, ebchin commented on src/tests/tribol_mfem_mortar_lm.cpp
> +  mfem::Device device( "cuda" );
check if `TRIBOL_USE_CUDA` should be here instead

2025-11-06 18:42 UTC, ebchin commented on src/tribol/common/BasicTypes.hpp
> +#error "TRIBOL_USE_CUDA or TRIBOL_USE_HIP but __device__ is undefined.  Check include files"
`TRIBOL_USE_HIP but __device__ is undefined.`

2025-11-06 19:00 UTC, ebchin commented on src/tribol/mesh/MfemData.cpp
> +    // Tribol only computes on host
no!

2025-11-06 19:00 UTC, ebchin commented on src/tribol/mesh/MfemData.cpp
> +    auto data = GetRedecompGridFn().HostRead();
get rid of comment and fix L250 and L264

2025-11-06 19:37 UTC, ebchin commented on src/tests/redecomp_transfer.cpp
> +  xfer_quad_fn_->Read();
Got rid of these

2025-11-06 19:47 UTC, ebchin commented on src/tests/tribol_mfem_mortar_lm.cpp
> +  mfem::Device device( "cuda" );
fixed.  matches common plane test now.

2025-11-06 19:49 UTC, ebchin commented on src/tribol/common/BasicTypes.hpp
> +#error "TRIBOL_USE_CUDA or TRIBOL_USE_HIP but __device__ is undefined.  Check include files"
this can be removed, it was copy/pasted from L55

2025-11-06 21:33 UTC, ebchin commented on src/tests/tribol_mfem_mortar_lm.cpp
> +  mfem::Device device( "cuda" );
Actually fixed now.  Forgot for a second there we don't support GPU for mortar.

2025-11-06 23:08 UTC, srwopschall approved these changes

2025-11-10 19:32 UTC, merged